name: Deploy to VPS

on:
    push:
        branches: ["main", "master"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  port: ${{ secrets.VPS_PORT }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      set -e
                      cd /opt/bots/suggestions
                      git fetch --all
                      git reset --hard origin/master

                      /opt/bots/suggestions/venv/bin/python -m pip install -r requirements.txt

                      sudo systemctl restart discord-bot@suggestions.service
                      sudo systemctl status discord-bot@suggestions.service --no-pager -l | tail -n 50
